export default {
  port: process.env.PORT || 5000,
  mongoUri: process.env.MONGO_URI,
  sendgridApiKey: process.env.SENDGRID_API_KEY || '',
  fromEmail: process.env.FROM_EMAIL || '',
  toEmail: process.env.TO_EMAIL || '',
  publicKey: process.env.PUBLIC_KEY || '',
  privateKey: process.env.PRIVATE_KEY || '',
  logoAddress: process.env.LOGO_ADDRESS || '',
  addressServer: process.env.ADDRESS_SERVER || '',
  keys: ['dfkjndsnd', 'asbjbs'],
  redisServer: process.env.REDIS_ADDRESS || '',
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME || '',
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY || '',
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET || '',
  mapsProvider: process.env.MAPS_PROVIDER || 'google',
  mapsApiKey: process.env.MAPS_API_KEY || '',
  tkLatitude: process.env.TK_LATITUDE || 0,
  tkLongitude: process.env.TK_LONGITUDE || 0,
  cors: process.env.CORS || 'http://localhost:3000',
  cookieDomain: process.env.COOKIE_DOMAIN || 'localhost',
  enterpriseName: process.env.ENTERPRISE_NAME || 'TK Boutique',
  moncashMode: process.env.MONCASH_MODE || 'sandbox',
  moncashClient: process.env.MONCASH_CLIENT || '',
  moncashSecret: process.env.MONCASH_SECRET || '',
  stripeKey: process.env.STRIPE_KEY || '',
};
