export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const ACTIVATE_ACCOUNT_REQUEST = 'ACTIVATE_ACCOUNT_REQUEST';
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAIL = 'ACTIVATE_ACCOUNT_FAIL';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const RESEND_VALIDATION_EMAIL_REQUEST =
  'RESEND_VALIDATION_EMAIL_REQUEST';
export const RESEND_VALIDATION_EMAIL_SUCCESS =
  'RESEND_VALIDATION_EMAIL_SUCCESS';
export const RESEND_VALIDATION_EMAIL_FAILED = 'RESEND_VALIDATION_EMAIL_FAILED';

export const SEND_RESET_PASSWORD_EMAIL_REQUEST =
  'SEND_RESET_PASSWORD_EMAIL_REQUEST';
export const SEND_RESET_PASSWORD_EMAIL_SUCCESS =
  'SEND_RESET_PASSWORD_EMAIL_SUCCESS';
export const SEND_RESET_PASSWORD_EMAIL_FAILED =
  'SEND_RESET_PASSWORD_EMAIL_FAILED';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
