export const CONTACT_REQUEST = 'CONTACT_REQUEST';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAILED = 'CONTACT_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
