export const CURRENCY_LIST_REQUEST = 'CURRENCY_LIST_REQUEST';
export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS';
export const CURRENCY_LIST_FAILED = 'CURRENCY_LIST_FAILED';

export const CURRENCY_CREATE_REQUEST = 'CURRENCY_CREATE_REQUEST';
export const CURRENCY_CREATE_SUCCESS = 'CURRENCY_CREATE_SUCCESS';
export const CURRENCY_CREATE_FAILED = 'CURRENCY_CREATE_FAILED';
export const CURRENCY_CREATE_RESET = 'CURRENCY_CREATE_RESET';

export const CURRENCY_DETAIL_REQUEST = 'CURRENCY_DETAIL_REQUEST';
export const CURRENCY_DETAIL_SUCCESS = 'CURRENCY_DETAIL_SUCCESS';
export const CURRENCY_DETAIL_FAILED = 'CURRENCY_DETAIL_FAILED';
export const CURRENCY_DETAIL_RESET = 'CURRENCY_DETAIL_RESET';

export const CURRENCY_UPDATE_REQUEST = 'CURRENCY_UPDATE_REQUEST';
export const CURRENCY_UPDATE_SUCCESS = 'CURRENCY_UPDATE_SUCCESS';
export const CURRENCY_UPDATE_FAILED = 'CURRENCY_UPDATE_FAILED';
export const CURRENCY_UPDATE_RESET = 'CURRENCY_UPDATE_RESET';

export const CURRENCY_DELETE_REQUEST = 'CURRENCY_DELETE_REQUEST';
export const CURRENCY_DELETE_SUCCESS = 'CURRENCY_DELETE_SUCCESS';
export const CURRENCY_DELETE_FAILED = 'CURRENCY_DELETE_FAILED';

export const CURRENCY_MAKE_PRINCIPAL_REQUEST =
  'CURRENCY_MAKE_PRINCIPAL_REQUEST';
export const CURRENCY_MAKE_PRINCIPAL_SUCCESS =
  'CURRENCY_MAKE_PRINCIPAL_SUCCESS';
export const CURRENCY_MAKE_PRINCIPAL_FAILED = 'CURRENCY_MAKE_PRINCIPAL_FAILED';

export const CURRENCY_UNMAKE_PRINCIPAL_REQUEST =
  'CURRENCY_UNMAKE_PRINCIPAL_REQUEST';
export const CURRENCY_UNMAKE_PRINCIPAL_SUCCESS =
  'CURRENCY_UNMAKE_PRINCIPAL_SUCCESS';
export const CURRENCY_UNMAKE_PRINCIPAL_FAILED =
  'CURRENCY_UNMAKE_PRINCIPAL_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
