export const MONCASH_CREATE_REQUEST = 'MONCASH_CREATE_REQUEST';
export const MONCASH_CREATE_SUCCESS = 'MONCASH_CREATE_SUCCESS';
export const MONCASH_CREATE_FAILED = 'MONCASH_CREATE_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
