export const ORDERS_LIST_REQUEST = 'ORDERS_LIST_REQUEST';
export const ORDERS_LIST_SUCCESS = 'ORDERS_LIST_SUCCESS';
export const ORDERS_LIST_FAILED = 'ORDERS_LIST_FAILED';

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';
export const ORDER_DETAIL_FAILED = 'ORDER_DETAIL_FAILED';
export const ORDER_DETAIL_RESET = 'ORDER_DETAIL_RESET';

export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST';
export const ORDER_UPDATE_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS';
export const ORDER_UPDATE_STATUS_FAILED = 'ORDER_UPDATE_STATUS_FAILED';

export const ORDER_CREATE_ADMIN_REQUEST = 'ORDER_CREATE_ADMIN_REQUEST';
export const ORDER_CREATE_ADMIN_SUCCESS = 'ORDER_CREATE_ADMIN_SUCCESS';
export const ORDER_CREATE_ADMIN_FAILED = 'ORDER_CREATE_ADMIN_FAILED';

export const ADD_SHIPPING_DETAIL = 'ADD_SHIPPING_DETAIL';
export const ADD_PAYMENT_DETAIL = 'ADD_PAYMENT_DETAIL';
export const CLEAR_ORDER_INFOS = 'CLEAR_ORDER_INFOS';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
