export const SHIPPING_DETAIL_REQUEST = 'SHIPPING_DETAIL_REQUEST';
export const SHIPPING_DETAIL_SUCCESS = 'SHIPPING_DETAIL_SUCCESS';
export const SHIPPING_DETAIL_FAILED = 'SHIPPING_DETAIL_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
