export const STRIPE_INTENT_REQUEST = 'STRIPE_INTENT_REQUEST';
export const STRIPE_INTENT_SUCCESS = 'STRIPE_INTENT_SUCCESS';
export const STRIPE_INTENT_FAILED = 'STRIPE_INTENT_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
