export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAILED = 'USER_PROFILE_UPDATE_FAILED';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED';

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_FAILED = 'USER_DETAIL_FAILED';
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET';

export const USER_CHANGE_TYPE_REQUEST = 'USER_CHANGE_TYPE_REQUEST';
export const USER_CHANGE_TYPE_SUCCESS = 'USER_CHANGE_TYPE_SUCCESS';
export const USER_CHANGE_TYPE_FAILED = 'USER_CHANGE_TYPE_FAILED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
